//! Extractor-owned fetch and artifact facts.

use ratatoskr_identifiers::{BlobRef, DigestAlgorithm};
use sqlx::PgPool;

use crate::PersistenceError;

const OWNER: &str = "ratatoskr-extractor";

/// One completed network fetch.
#[derive(Debug)]
pub struct FetchRecord<'a> {
    /// Owning extraction run.
    pub run_id: uuid::Uuid,
    /// Owner that must match the run.
    pub owner_id: uuid::Uuid,
    /// Redirect-resolved URL.
    pub final_url: &'a str,
    /// Final HTTP status.
    pub http_status: u16,
    /// Effective media type.
    pub media_type: &'a str,
    /// Compressed bytes received.
    pub wire_bytes: u64,
    /// Decoded bytes stored.
    pub decoded_bytes: u64,
    /// Network attempts used.
    pub attempts: u32,
    /// Cache decision.
    pub cache_outcome: &'a str,
    /// Safe validator, when present.
    pub etag: Option<&'a str>,
    /// Safe modification validator, when present.
    pub last_modified: Option<&'a str>,
}

/// Artifact role within one extraction run.
#[derive(Debug, Clone, Copy)]
pub enum ArtifactKind {
    /// Original fetched response body.
    RawSource,
    /// Canonical serialized Document IR.
    DocumentIr,
    /// Safe diagnostic artifact.
    Diagnostics,
}

impl ArtifactKind {
    const fn as_str(self) -> &'static str {
        match self {
            Self::RawSource => "raw_source",
            Self::DocumentIr => "document_ir",
            Self::Diagnostics => "diagnostics",
        }
    }
}

/// One extractor-owned content-addressed artifact.
#[derive(Debug)]
pub struct ArtifactRecord<'a> {
    /// Owning extraction run.
    pub run_id: uuid::Uuid,
    /// Owner that must match the run.
    pub owner_id: uuid::Uuid,
    /// Artifact role.
    pub kind: ArtifactKind,
    /// Content-addressed reference.
    pub reference: &'a BlobRef,
}

/// One evaluated extraction candidate.
#[derive(Debug)]
pub struct CandidateRecord<'a> {
    /// Owning extraction run.
    pub run_id: uuid::Uuid,
    /// Owner that must match the run.
    pub owner_id: uuid::Uuid,
    /// Deterministic extraction strategy.
    pub strategy: &'a str,
    /// Extractor implementation version.
    pub extractor_version: &'a str,
    /// Strategy metrics.
    pub metrics: &'a serde_json::Map<String, serde_json::Value>,
    /// Candidate quality score in the unit interval.
    pub score: Option<f64>,
    /// Bounded quality decision reasons.
    pub reasons: &'a [serde_json::Value],
    /// Whether this candidate became the accepted document.
    pub selected: bool,
    /// Optional artifact generated by the candidate.
    pub artifact_id: Option<uuid::Uuid>,
}

/// Records one fetch idempotently by run.
///
/// # Errors
///
/// Returns an error when a size overflows or `PostgreSQL` rejects the fact.
pub async fn record_fetch(pool: &PgPool, record: &FetchRecord<'_>) -> Result<(), PersistenceError> {
    let wire_bytes =
        i64::try_from(record.wire_bytes).map_err(|_| PersistenceError::ValueOverflow)?;
    let decoded_bytes =
        i64::try_from(record.decoded_bytes).map_err(|_| PersistenceError::ValueOverflow)?;
    let attempts = i32::try_from(record.attempts).map_err(|_| PersistenceError::ValueOverflow)?;
    let result = sqlx::query(
        "insert into extractor.fetches
             (fetch_id, run_id, final_url, http_status, media_type, wire_bytes, decoded_bytes,
              attempts, cache_outcome, etag, last_modified, fetched_at)
         select $1, $2, $4, $5, $6, $7, $8, $9, $10, $11, $12, transaction_timestamp()
           from extractor.extraction_runs
          where run_id = $2 and owner_id = $3
         on conflict (run_id) do update set
             final_url = excluded.final_url, http_status = excluded.http_status,
             media_type = excluded.media_type, wire_bytes = excluded.wire_bytes,
             decoded_bytes = excluded.decoded_bytes, attempts = excluded.attempts,
             cache_outcome = excluded.cache_outcome, etag = excluded.etag,
             last_modified = excluded.last_modified",
    )
    .bind(uuid::Uuid::now_v7())
    .bind(record.run_id)
    .bind(record.owner_id)
    .bind(record.final_url)
    .bind(i32::from(record.http_status))
    .bind(record.media_type)
    .bind(wire_bytes)
    .bind(decoded_bytes)
    .bind(attempts)
    .bind(record.cache_outcome)
    .bind(record.etag)
    .bind(record.last_modified)
    .execute(pool)
    .await
    .map_err(PersistenceError::Query)?;
    owned(&result)
}

/// Records one artifact reference idempotently by run and kind.
///
/// # Errors
///
/// Returns an error for a foreign reference, unsupported digest, overflow, or database failure.
pub async fn record_artifact(
    pool: &PgPool,
    record: &ArtifactRecord<'_>,
) -> Result<(), PersistenceError> {
    if record.reference.owner_service.as_str() != OWNER
        || !matches!(record.reference.digest.algorithm, DigestAlgorithm::Sha256)
    {
        return Err(PersistenceError::InvalidArtifact);
    }
    let length = i64::try_from(record.reference.length_bytes)
        .map_err(|_| PersistenceError::ValueOverflow)?;
    let result = sqlx::query(
        "insert into extractor.artifacts
             (artifact_id, run_id, kind, owner_service, digest_algorithm, digest_hex, media_type,
              length_bytes, created_at)
         select $1, $2, $4, $5, 'sha256', $6, $7, $8, transaction_timestamp()
           from extractor.extraction_runs
          where run_id = $2 and owner_id = $3
         on conflict (run_id, kind) do update set
             owner_service = excluded.owner_service, digest_algorithm = excluded.digest_algorithm,
             digest_hex = excluded.digest_hex, media_type = excluded.media_type,
             length_bytes = excluded.length_bytes",
    )
    .bind(uuid::Uuid::now_v7())
    .bind(record.run_id)
    .bind(record.owner_id)
    .bind(record.kind.as_str())
    .bind(OWNER)
    .bind(record.reference.digest.hex.as_str())
    .bind(record.reference.media_type.as_str())
    .bind(length)
    .execute(pool)
    .await
    .map_err(PersistenceError::Query)?;
    owned(&result)
}

/// Records one future extraction candidate idempotently by its natural run key.
///
/// # Errors
///
/// Returns an error when `PostgreSQL` rejects the fact.
pub async fn record_candidate(
    pool: &PgPool,
    record: &CandidateRecord<'_>,
) -> Result<(), PersistenceError> {
    let result = sqlx::query(
        "insert into extractor.candidates
             (candidate_id, run_id, strategy, extractor_version, metrics, score, reasons,
              selected, artifact_id, created_at)
         select $1, $2, $4, $5, $6, $7, $8, $9, $10, transaction_timestamp()
           from extractor.extraction_runs
          where run_id = $2 and owner_id = $3
         on conflict (run_id, strategy, extractor_version) do update set
             metrics = excluded.metrics, score = excluded.score, reasons = excluded.reasons,
             selected = excluded.selected, artifact_id = excluded.artifact_id",
    )
    .bind(uuid::Uuid::now_v7())
    .bind(record.run_id)
    .bind(record.owner_id)
    .bind(record.strategy)
    .bind(record.extractor_version)
    .bind(serde_json::Value::Object(record.metrics.clone()))
    .bind(record.score)
    .bind(serde_json::Value::Array(record.reasons.to_vec()))
    .bind(record.selected)
    .bind(record.artifact_id)
    .execute(pool)
    .await
    .map_err(PersistenceError::Query)?;
    owned(&result)
}

fn owned(result: &sqlx::postgres::PgQueryResult) -> Result<(), PersistenceError> {
    if result.rows_affected() == 0 {
        Err(PersistenceError::OwnerMismatch)
    } else {
        Ok(())
    }
}
