//! Player-response extraction and caption-track selection tests against synthetic pages.

use extractor_youtube::CaptionTrack;
use extractor_youtube::TrackKind;
use extractor_youtube::YoutubeError;
use extractor_youtube::YoutubeLimits;
use extractor_youtube::extract_player_response;
use extractor_youtube::select_track;

const HAPPY_PAGE: &str = include_str!("fixtures/player-happy.html");
const NO_MARKER_PAGE: &str = include_str!("fixtures/player-no-marker.html");
const UNBALANCED_PAGE: &str = include_str!("fixtures/player-unbalanced-braces.html");
const RUNS_NAME_PAGE: &str = include_str!("fixtures/player-runs-name.html");

fn limits() -> YoutubeLimits {
    YoutubeLimits {
        max_page_bytes: 1 << 20,
        max_track_bytes: 1 << 20,
        max_blocks: 2_000,
        max_segments: 20_000,
        max_segment_characters: 4_000,
    }
}

fn tiny_page_budget() -> YoutubeLimits {
    YoutubeLimits {
        max_page_bytes: 64,
        ..limits()
    }
}

fn track(language_code: &str, kind: TrackKind, base_url: &str) -> CaptionTrack {
    CaptionTrack {
        language_code: language_code.to_owned(),
        name: None,
        kind,
        base_url: base_url.to_owned(),
    }
}

fn languages(codes: &[&str]) -> Vec<String> {
    codes.iter().map(|code| (*code).to_owned()).collect()
}

#[test]
fn happy_watch_page_yields_metadata_and_both_advertised_tracks() {
    let meta = extract_player_response(HAPPY_PAGE, &limits())
        .expect("happy page parses under the generous budget");

    assert_eq!(meta.title.as_deref(), Some("Test Video Title"));
    assert_eq!(meta.channel.as_deref(), Some("Example Channel"));
    assert_eq!(meta.duration_seconds, Some(2123));

    assert_eq!(meta.tracks.len(), 2, "both advertised tracks are parsed");
    let english = &meta.tracks[0];
    assert_eq!(english.language_code, "en");
    assert_eq!(english.name.as_deref(), Some("English"));
    assert_eq!(english.kind, TrackKind::Manual);
    assert_eq!(
        english.base_url,
        "https://www.youtube.com/api/timedtext?x=1"
    );

    let russian = &meta.tracks[1];
    assert_eq!(russian.language_code, "ru");
    assert_eq!(russian.name.as_deref(), Some("Russian (auto)"));
    assert_eq!(russian.kind, TrackKind::AutoGenerated);
}

#[test]
fn page_without_the_player_response_marker_is_a_schema_error() {
    let error = extract_player_response(NO_MARKER_PAGE, &limits())
        .expect_err("a page without the marker names no player response");
    assert!(matches!(error, YoutubeError::Schema));
}

#[test]
fn unbalanced_braces_inside_strings_fail_as_schema_without_scanning_forever() {
    let error = extract_player_response(UNBALANCED_PAGE, &limits())
        .expect_err("an unterminated string must fail closed as a schema error");
    assert!(matches!(error, YoutubeError::Schema));
}

#[test]
fn page_over_the_byte_budget_is_rejected_before_parsing() {
    // The same page parses fine under the generous budget in the happy-path test, so a
    // ResourceLimit here proves the budget check runs before any parsing work.
    let error = extract_player_response(HAPPY_PAGE, &tiny_page_budget())
        .expect_err("a page over the byte budget is rejected");
    assert!(matches!(error, YoutubeError::ResourceLimit));
}

#[test]
fn runs_style_track_name_parses_to_its_text() {
    let meta = extract_player_response(RUNS_NAME_PAGE, &limits())
        .expect("runs-name page parses under the generous budget");

    assert_eq!(meta.tracks.len(), 1);
    assert_eq!(meta.tracks[0].name.as_deref(), Some("English"));
}

#[test]
fn deterministic_double_call_produces_identical_metadata() {
    let first = extract_player_response(HAPPY_PAGE, &limits()).expect("first call succeeds");
    let second = extract_player_response(HAPPY_PAGE, &limits()).expect("second call succeeds");
    assert_eq!(first, second);
}

#[test]
fn manual_track_beats_auto_generated_within_the_top_language() {
    let tracks = [
        track(
            "en",
            TrackKind::AutoGenerated,
            "https://www.youtube.com/api/timedtext?x=auto",
        ),
        track(
            "en",
            TrackKind::Manual,
            "https://www.youtube.com/api/timedtext?x=manual",
        ),
    ];

    let selected = select_track(&tracks, &languages(&["en"])).expect("a manual en track exists");

    assert_eq!(
        selected.base_url,
        "https://www.youtube.com/api/timedtext?x=manual"
    );
}

#[test]
fn language_preference_order_dominates_track_kind() {
    let tracks = [
        track(
            "en",
            TrackKind::AutoGenerated,
            "https://www.youtube.com/api/timedtext?x=en-auto",
        ),
        track(
            "de",
            TrackKind::Manual,
            "https://www.youtube.com/api/timedtext?x=de-manual",
        ),
    ];

    let selected =
        select_track(&tracks, &languages(&["en", "de"])).expect("the top language has a track");

    assert_eq!(selected.language_code, "en");
    assert_eq!(selected.kind, TrackKind::AutoGenerated);
}

#[test]
fn auto_generated_only_top_language_is_still_selected() {
    let tracks = [track(
        "ru",
        TrackKind::AutoGenerated,
        "https://www.youtube.com/api/timedtext?x=ru-asr",
    )];

    let selected = select_track(&tracks, &languages(&["ru"])).expect("an asr-only track is usable");

    assert_eq!(selected.kind, TrackKind::AutoGenerated);
    assert_eq!(selected.language_code, "ru");
}

#[test]
fn an_empty_track_list_is_no_transcript() {
    let error = select_track(&[], &languages(&["en"])).expect_err("no tracks means no transcript");
    assert!(matches!(error, YoutubeError::NoTranscript));
}

#[test]
fn usable_tracks_that_match_no_preferred_language_are_no_language_match() {
    let tracks = [
        track(
            "de",
            TrackKind::Manual,
            "https://www.youtube.com/api/timedtext?x=de",
        ),
        track(
            "fr",
            TrackKind::AutoGenerated,
            "https://www.youtube.com/api/timedtext?x=fr",
        ),
    ];

    let error = select_track(&tracks, &languages(&["en"]))
        .expect_err("usable tracks exist but none matches the preference");
    assert!(matches!(error, YoutubeError::NoLanguageMatch));
}

#[test]
fn insecure_or_foreign_host_tracks_are_ignored_before_matching() {
    let tracks = [
        track(
            "en",
            TrackKind::Manual,
            "http://www.youtube.com/api/timedtext?x=insecure",
        ),
        track(
            "en",
            TrackKind::Manual,
            "https://evil.example.com/api/timedtext?x=foreign",
        ),
    ];

    let error = select_track(&tracks, &languages(&["en"]))
        .expect_err("no usable location exists, so nothing may be returned");
    assert!(matches!(error, YoutubeError::NoTranscript));
}
