//! Embedded player-response extraction and caption-track selection.

use crate::YoutubeError;
use crate::YoutubeLimits;
use crate::identity::is_documented_host;
use serde::Deserialize;

/// Marker that introduces the embedded player response inside watch-page HTML.
const PLAYER_RESPONSE_MARKER: &str = "ytInitialPlayerResponse";

/// Whether a caption track was manually authored or machine generated.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum TrackKind {
    /// Authored by the uploader or a human contributor.
    Manual,
    /// Produced by automatic speech recognition.
    AutoGenerated,
}

/// One advertised caption track with its retrieval location.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct CaptionTrack {
    /// Track language tag as advertised.
    pub language_code: String,
    /// Human-readable track name when provided.
    pub name: Option<String>,
    /// Manual versus auto-generated origin.
    pub kind: TrackKind,
    /// Absolute timed-text location advertised by the player response.
    pub base_url: String,
}

/// Bounded video metadata extracted from the embedded player response.
#[derive(Debug, Clone, PartialEq, Eq, Default)]
pub struct PlayerMeta {
    /// Video title when present.
    pub title: Option<String>,
    /// Channel name when present.
    pub channel: Option<String>,
    /// Video duration in seconds when present.
    pub duration_seconds: Option<u64>,
    /// Advertised caption tracks in player order.
    pub tracks: Vec<CaptionTrack>,
}

/// Tolerant view of the embedded player response; unknown fields are ignored.
#[derive(Debug, Deserialize)]
struct PlayerResponse {
    #[serde(rename = "videoDetails", default)]
    video_details: Option<VideoDetails>,
    #[serde(default)]
    captions: Option<Captions>,
}

/// Tolerant view of the `videoDetails` container.
#[derive(Debug, Deserialize, Default)]
struct VideoDetails {
    #[serde(default)]
    title: Option<String>,
    #[serde(default)]
    author: Option<String>,
    /// Server-declared duration as a decimal string.
    #[serde(rename = "lengthSeconds", default)]
    length_seconds: Option<String>,
}

/// Tolerant view of the `captions` container.
#[derive(Debug, Deserialize)]
struct Captions {
    #[serde(rename = "playerCaptionTracks", default)]
    player_caption_tracks: Vec<TrackEntry>,
}

/// Tolerant view of one advertised caption track entry.
#[derive(Debug, Deserialize)]
struct TrackEntry {
    #[serde(rename = "baseUrl", default)]
    base_url: Option<String>,
    #[serde(rename = "languageCode", default)]
    language_code: Option<String>,
    #[serde(default)]
    name: Option<TrackName>,
    #[serde(default)]
    kind: Option<String>,
}

/// Tolerant view of a track name in either the simple or the runs form.
#[derive(Debug, Deserialize)]
struct TrackName {
    #[serde(rename = "simpleText", default)]
    simple_text: Option<String>,
    #[serde(default)]
    runs: Option<Vec<TextRun>>,
}

/// One styled text run inside a runs-form name.
#[derive(Debug, Deserialize)]
struct TextRun {
    #[serde(default)]
    text: Option<String>,
}

/// Extracts bounded video metadata from one watch-page HTML payload.
///
/// The byte budget is checked before any parsing work. The JSON object assigned to the
/// player-response marker is located with an escape-aware brace scan under a hard character
/// cap, then decoded tolerantly: unknown fields are ignored and absent optional fields stay
/// absent. Identical input yields identical output on every call.
///
/// # Errors
///
/// Returns [`YoutubeError`] when the page exceeds its byte budget, carries no usable
/// player response, or violates the required schema.
pub fn extract_player_response(
    page_html: &str,
    limits: &YoutubeLimits,
) -> Result<PlayerMeta, YoutubeError> {
    if page_html.len() > limits.max_page_bytes {
        return Err(YoutubeError::ResourceLimit);
    }
    let payload = embedded_json_payload(page_html, limits)?;
    let response = serde_json::from_slice::<PlayerResponse>(payload.as_bytes())
        .map_err(|_| YoutubeError::Schema)?;
    let details = response.video_details.unwrap_or_default();
    Ok(PlayerMeta {
        title: details.title,
        channel: details.author,
        duration_seconds: details
            .length_seconds
            .as_deref()
            .and_then(|seconds| seconds.parse::<u64>().ok()),
        tracks: response.captions.map_or_else(Vec::new, |captions| {
            advertised_tracks(captions.player_caption_tracks)
        }),
    })
}

/// Selects one caption track under an explicit ordered language preference.
///
/// Tracks whose location is not an HTTPS URL on a documented `YouTube` host are ignored before
/// matching, so they are never fetched. Within one language a manual track beats an
/// auto-generated one; the first match under the preference order wins.
///
/// # Errors
///
/// Returns [`YoutubeError::NoTranscript`] when no usable track exists and
/// [`YoutubeError::NoLanguageMatch`] when tracks exist but none matches the preference.
pub fn select_track<'a>(
    tracks: &'a [CaptionTrack],
    languages: &[String],
) -> Result<&'a CaptionTrack, YoutubeError> {
    let usable: Vec<&CaptionTrack> = tracks
        .iter()
        .filter(|track| has_usable_location(&track.base_url))
        .collect();
    if usable.is_empty() {
        return Err(YoutubeError::NoTranscript);
    }
    for language in languages {
        let manual = usable
            .iter()
            .copied()
            .find(|track| track.kind == TrackKind::Manual && track.language_code == *language);
        if let Some(selected) = manual {
            return Ok(selected);
        }
        let generated = usable.iter().copied().find(|track| {
            track.kind == TrackKind::AutoGenerated && track.language_code == *language
        });
        if let Some(selected) = generated {
            return Ok(selected);
        }
    }
    Err(YoutubeError::NoLanguageMatch)
}

/// Locates the JSON object assigned to the player-response marker and returns its exact text.
fn embedded_json_payload(page_html: &str, limits: &YoutubeLimits) -> Result<String, YoutubeError> {
    let marker_start = page_html
        .find(PLAYER_RESPONSE_MARKER)
        .ok_or(YoutubeError::Schema)?;
    let after_marker = page_html
        .get(marker_start + PLAYER_RESPONSE_MARKER.len()..)
        .ok_or(YoutubeError::Schema)?;
    let assignment = after_marker
        .char_indices()
        .find(|(_, ch)| !ch.is_whitespace())
        .filter(|(_, ch)| *ch == '=')
        .ok_or(YoutubeError::Schema)?;
    let tail = after_marker
        .get(assignment.0 + '='.len_utf8()..)
        .ok_or(YoutubeError::Schema)?;
    balanced_object_text(
        tail,
        marker_start + PLAYER_RESPONSE_MARKER.chars().count(),
        limits,
    )
}

/// Scans one brace-balanced JSON object honoring string escapes under a hard character cap.
///
/// The cap counts characters from the marker start, so a hostile payload can never make the
/// scan run past the declared budget; running out of input before the object closes is a
/// schema failure rather than a panic.
fn balanced_object_text(
    tail: &str,
    scanned_before_tail: usize,
    limits: &YoutubeLimits,
) -> Result<String, YoutubeError> {
    let mut depth = 0usize;
    let mut in_string = false;
    let mut escaped = false;
    let mut scanned = scanned_before_tail;
    for (offset, ch) in tail.char_indices() {
        scanned += 1;
        if scanned > limits.max_page_bytes {
            return Err(YoutubeError::Schema);
        }
        if in_string {
            if escaped {
                escaped = false;
            } else if ch == '\\' {
                escaped = true;
            } else if ch == '"' {
                in_string = false;
            }
            continue;
        }
        match ch {
            '"' => in_string = true,
            '{' => depth += 1,
            '}' => {
                if depth == 0 {
                    return Err(YoutubeError::Schema);
                }
                depth -= 1;
                if depth == 0 {
                    return tail
                        .get(..offset + ch.len_utf8())
                        .map(str::to_owned)
                        .ok_or(YoutubeError::Schema);
                }
            }
            _ => {}
        }
    }
    Err(YoutubeError::Schema)
}

/// Converts tolerant track entries into advertised caption tracks in player order.
///
/// Entries without both a location and a language tag cannot be represented as a
/// [`CaptionTrack`] and are skipped deterministically.
fn advertised_tracks(entries: Vec<TrackEntry>) -> Vec<CaptionTrack> {
    entries
        .into_iter()
        .filter_map(|entry| {
            let base_url = entry.base_url?;
            let language_code = entry.language_code?;
            let kind = if entry.kind.as_deref() == Some("asr") {
                TrackKind::AutoGenerated
            } else {
                TrackKind::Manual
            };
            Some(CaptionTrack {
                language_code,
                name: track_name(entry.name),
                kind,
                base_url,
            })
        })
        .collect()
}

/// Resolves a track name from either the simple or the runs form.
fn track_name(name: Option<TrackName>) -> Option<String> {
    let name = name?;
    name.simple_text.or_else(|| {
        name.runs?
            .into_iter()
            .find_map(|run| run.text.filter(|text| !text.is_empty()))
    })
}

/// Whether a track location is an HTTPS URL on a documented `YouTube` host.
fn has_usable_location(base_url: &str) -> bool {
    let Ok(parsed) = url::Url::parse(base_url) else {
        return false;
    };
    if parsed.scheme() != "https" {
        return false;
    }
    let Some(host) = parsed.host_str() else {
        return false;
    };
    let lowered = host.to_ascii_lowercase();
    is_documented_host(&lowered, "youtube.com")
        || is_documented_host(&lowered, "youtu.be")
        || is_documented_host(&lowered, "youtube-nocookie.com")
}
